language: python
cache:
  - ccache
  - directories:
    - $HOME/.ccache
  - pip
matrix:
  include:
  - dist: trusty
    python: 2.7
  - dist: trusty
    python: 3.5
  - dist: trusty
    python: 3.6
  - dist: xenial
    python: 2.7
  - dist: xenial
    python: 3.5
  - dist: xenial
    python: 3.6
  - os: osx
    language: generic
before_install:
  - export SOEXT=so
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then
      brew update > /dev/null ;
      brew install ccache ;
      SOEXT=dylib ;
      PATH="/usr/local/share/python/:$PATH" ;
    fi
  - ccache -s
# version=master or version=f123f12f3 to select a specific version
  - CXX="ccache g++" .travis/install.plumed version=master
  - ccache -s
  - pip install numpy cython
  - pip install nose

install:
  - pip install -e .

script:
  - export PLUMED_KERNEL=$HOME/opt/lib/libplumedKernel.$SOEXT
  - nosetests -v
